[package]
name = "calculator3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evalexpr = "10.0.0"
regex = "1.8.3"
sycamore = "0.9.0-beta.1"
